### ISSUE TITLE
Build Error "The Broccoli Plugin: [StyleLinter] failed"

### ISSUE THREAD

**Issue by SheriefAlaa** [HospitalRun/hospitalrun-frontend#798]
**Expected behavior:**

Run hospitalrun-frontend

**Actual behavior:**

Build Error. Log ahead..

```
Checking CouchDB...Starting ember server
WARNING: Node v7.0.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/patients/edit/template.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/appointments.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/inventory.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/labs.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/medication.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/visits/edit/template.js" as it exceeds the max of "100KB".
(node:4792) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
TypeError: Cannot read property 'length' of undefined
    at exports.default (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-stylelint/node_modules/stylelint/dist/utils/isStandardSyntaxDeclaration.js:28:38)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-stylelint/node_modules/stylelint/dist/rules/declaration-colon-space-after/index.js:54:49
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:192:28
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:148:26
    at AtRule.each (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:114:22)
    at AtRule.walk (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:147:21)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkDecls (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:190:25)
File: styles/_bootstrap.scss
The Broccoli Plugin: [StyleLinter] failed with:
TypeError: Cannot read property 'errored' of undefined
    at StyleLinter.postProcess (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-stylelint/index.js:137:12)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:21:21
    at initializePromise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:20:14
    at tryCatch (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at StyleLinter.Plugin (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at StyleLinter.Filter [as constructor] (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new StyleLinter (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-stylelint/index.js:66:10)
    at Class.lintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/index.js:53:14)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:603:20
    at Array.map (native)
    at EmberApp.addonLintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:601:36)
    at EmberApp.lintTestTrees (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1158:24)
    at EmberApp.appTests (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1129:51)
    at EmberApp.test (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1115:26)

```

**OS and Browser:**

Chrome. Ubuntu 14.04 vagrant box on OS X.

**Comment by SheriefAlaa** [comment]
I downgraded node from version 7.0.0 to 6.0.0 then rebuild node-sass and still get the same build error.

**Comment by jkleinsc** [comment]
@SheriefAlaa thanks for filing the issue.  I can reproduce and I will take a look at it.

**Comment by jkleinsc** [comment]
@SheriefAlaa if you get the latest from master this problem is now fixed.

**Comment by SheriefAlaa** [comment]
Still experiencing issues even after git pull on master, npm install (I made sure stylelint got updated).

error log:

```
styles/_bootstrap.scss (in /home/vagrant/code/hospitalrun-frontend/tmp/style_linter-input_base_path-rNFjVXIl.tmp/0)

The Broccoli Plugin: [StyleLinter] failed with:

TypeError: Cannot read property 'errored' of undefined
    at StyleLinter.postProcess (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/broccoli-stylelint/index.js:137:12)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:21:21
    at initializePromise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:20:14
    at tryCatch (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at StyleLinter.Plugin (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at StyleLinter.Filter [as constructor] (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new StyleLinter (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/broccoli-stylelint/index.js:66:10)
    at Class.module.exports.lintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/index.js:53:14)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:603:20
    at Array.map (native)
    at EmberApp.addonLintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:601:36)
    at EmberApp.lintTestTrees (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1158:24)
    at EmberApp.appTests (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1129:51)
    at EmberApp.test (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1115:26)
```

Thanks for you help.

**Comment by SheriefAlaa** [comment]
@jkleinsc Seems it all started here: https://github.com/billybonks/broccoli-stylelint/issues/18

I ran npm test and here's the output:

```
> ./script/test

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠸ Building[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/patients/edit/template.js" as it exceeds the max of "100KB".
⠙ Building[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/appointments.js" as it exceeds the max of "100KB".
⠹ Building[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/inventory.js" as it exceeds the max of "100KB".
⠸ Building[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/labs.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/medication.js" as it exceeds the max of "100KB".
⠹ Building[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/visits/edit/template.js" as it exceeds the max of "100KB".
⠼ BuildingTypeError: Cannot read property 'length' of undefined
    at exports.default (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/utils/isStandardSyntaxDeclaration.js:28:38)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/rules/declaration-colon-space-after/index.js:54:49
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:192:28
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:148:26
    at AtRule.each (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:114:22)
    at AtRule.walk (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:147:21)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkDecls (/home/vagrant/code/hospitalrun-frontend/node_modules/postcss/lib/container.js:190:25)
    at declarationColonSpaceChecker (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/rules/declaration-colon-space-after/index.js:52:8)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/rules/declaration-colon-space-after/index.js:19:5
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/postcssPlugin.js:124:46
    at Array.forEach (native)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/stylelint/dist/postcssPlugin.js:103:33
cleaning up...
Build failed.
File: styles/_bootstrap.scss
The Broccoli Plugin: [StyleLinter] failed with:
TypeError: Cannot read property 'errored' of undefined
    at StyleLinter.postProcess (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/broccoli-stylelint/index.js:137:12)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:21:21
    at initializePromise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/lib/strategies/default.js:20:14
    at tryCatch (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at StyleLinter.Plugin (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at StyleLinter.Filter [as constructor] (/home/vagrant/code/hospitalrun-frontend/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new StyleLinter (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/node_modules/broccoli-stylelint/index.js:66:10)
    at Class.module.exports.lintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli-stylelint/index.js:53:14)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:603:20
    at Array.map (native)
    at EmberApp.addonLintTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:601:36)
    at EmberApp.lintTestTrees (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1158:24)
    at EmberApp.appTests (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1129:51)
    at EmberApp.test (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1115:26)
    at EmberApp.toArray (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1647:61)
    at EmberApp.toTree (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/home/vagrant/code/hospitalrun-frontend/ember-cli-build.js:37:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/models/builder.js:70:19)
    at CoreObject.module.exports.Task.extend.init (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/models/builder.js:50:10)
    at CoreObject.superWrapper [as init] (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
    at CoreObject.module.exports.Task.extend.run (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/home/vagrant/code/hospitalrun-frontend/node_modules/ember-cli/lib/commands/test.js:164:27)
    at tryCatch (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at /home/vagrant/code/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:628:16
```

**Comment by jkleinsc** [comment]
@SheriefAlaa my apologies.  I thought it was fixed, but @billybonks needed to publish a new version of https://github.com/billybonks/ember-cli-stylelint which he has now done and that version has now just been updated in HospitalRun, so the problem should now be fixed.  Let me know if it still persists after getting the latest from master.

**Comment by SheriefAlaa** [comment]
@jkleinsc HR now runs on my local machine just fine using master. Thanks for your and @billybonks '.
